//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gummigrossisten.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class gummi_grossisten_se_dbEntities : DbContext
    {
        public gummi_grossisten_se_dbEntities()
            : base("name=gummi_grossisten_se_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<access> access { get; set; }
        public virtual DbSet<news> news { get; set; }
        public virtual DbSet<tire> tire { get; set; }
        public virtual DbSet<user> user { get; set; }
    }
}
