//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gummigrossisten.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tire
    {
        public int tireID { get; set; }
        public string brand { get; set; }
        public string dimension { get; set; }
        public string type { get; set; }
        public string season { get; set; }
        public string tirebearingcapacity { get; set; }
        public string rollingresistance { get; set; }
        public string breakingdistance { get; set; }
        public string sounddecibel { get; set; }
        public Nullable<decimal> inprice { get; set; }
        public Nullable<decimal> outpriceA { get; set; }
        public Nullable<decimal> outpriceB { get; set; }
        public Nullable<int> balance { get; set; }
    }
}
